### ISSUE TITLE
set the fitness predicted by the model as fitness to bad individuals

### ISSUE THREAD

**Issue by YingBi92** [martinpilat/gp-surrogate#1]
In the algo, in the ea_surrogate_simple function, 
     # set the fitness predicted by the model as fitness to bad individuals
why offspring[invalid_ix[ix]] = selected[invalid_ix[ix]]? why not assign the predict values preds to the offspring?

**Comment by martinpilat** [comment]
Sorry for the long time it took me to reply, I  did not get any notification about the issue and did not notice it. 

The comment in the code is also miss-leading, the bad individuals are in fact replaced by their parents, which effectively removes them from the population, as if they were never created. We cannot assign the predicted fitness to the individuals as in case the model over-estimates the fitness, we would use this prediction instead of the real fitness and it would never be re-computed. As the real fitness of these individuals is effectively unknown, it is better to remove them from the population. Because I wanted to keep the population size constant, they are just replaced by the parents.
